### ISSUE TITLE
Doesn't deploy accessories menu

### ISSUE THREAD

**Issue by Zilgyd** [Swackyy/Ohmega#3]
When I try to unequip the elytra I can't because the menu of accessories no show it when I click on the accessory button:

![2024-08-21_21-48-58](https://github.com/user-attachments/assets/ace841c7-9964-4146-8dfb-8b0d2091b9e7)

**Comment by Zilgyd** [comment]
Version used
Version:  Forge 1.21-51.0.33
Mod version: ohmega-1.2.2+forge-1.21-1.21.1.jar

**Comment by Swackyy** [comment]
I recently fixed a bug to do with this on servers only, but it should be working fine.

Edit: I have fixed the bug, it seems to have gotten past testing. I have archived the previous 1.2.2 versions and re-released, I will provide download links below. Sorry about this, but thank you for reporting as I had trouble replicating the bug myself, turns out I had already fixed it on 1.2.2 ports 1.20.4 and below, so it only affected 1.20.6 and above, including the version you were using.

New download links:
- [CurseForge](https://www.curseforge.com/minecraft/mc-mods/ohmega/files/5652427)
- [Modrinth](https://modrinth.com/mod/ohmega/version/DLYe8tM7)
